---
language: node_js
node_js:
  - 14

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  # install aws cli
  - wget https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
  - unzip awscli-bundle.zip -d download
  - ./download/awscli-bundle/install -b ~/bin/aws
  - rm -r download
  - rm awscli-bundle.zip

script:
  # export variables
  - export DOMAIN=designguide.me
  - export CLOUDFRONT_DISTRIBUTION_ID=$(aws cloudfront list-distributions | jq -r --arg DOMAIN "$DOMAIN" '.DistributionList.Items[] | select (.Aliases.Items[] == $DOMAIN) | .Id')

  # build SPA
  - npm run build

  # deploy to s3
  #- aws s3 sync ./dist s3://"$DOMAIN"

  # invalidate cloudfront
  #- aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths "/*"